name: CI

on:
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format Check
        run: npm run format:check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload Backend node_modules
        uses: actions/upload-artifact@v4
        with:
          name: backend-node-modules
          path: backend/node_modules

  test-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: infrastructure/package-lock.json

      - name: Download Backend node_modules
        uses: actions/download-artifact@v4
        with:
          name: backend-node-modules
          path: backend/node_modules

      - name: Install AWS CLI
        run: npm install -g aws-cdk

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format Check
        run: npm run format:check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: CDK Synth
        run: cdk synth -c config=dev

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build:test